### ISSUE TITLE
binance api error

### ISSUE THREAD

**Issue by bhzhu203** [JonathanElejalde/playing_with_btc#1]
docker run --net=host -v /home/bhzhu/source/BTC/playing_with_btc:/strategy -ti ml_strategy /bin/bash -c "cd strategy && python -W ignore app.py"
2021-03-22 09:36:05.223973: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-22 09:36:05.224000: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-22 09:36:06.869729: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-22 09:36:06.870091: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-03-22 09:36:06.870109: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-22 09:36:06.870179: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2021-03-22 09:36:06.870331: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-22 09:36:06.870597: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Loaded scaler and model for btc
Loaded scaler and model for eth
Loaded scaler and model for bnb
Loaded scaler and model for trx
Loaded scaler and model for ada
Loaded scaler and model for ltc
Loaded scaler and model for xrp
2021-03-22 09:45:03.858202: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-22 09:45:03.878296: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3997645000 Hz
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fd7f1847550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fd7f190aca0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 7 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fd7f07c29d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
            open_time name   symbol  threshold  prediction
0 2021-03-22 09:30:00  btc  BTCUSDT       0.85    0.893694
1 2021-03-22 09:30:00  eth  ETHUSDT       0.85    0.317630
2 2021-03-22 09:30:00  bnb  BNBUSDT       0.85    0.703798
3 2021-03-22 09:30:00  trx  TRXUSDT       0.85    0.447939
4 2021-03-22 09:30:00  ada  ADAUSDT       0.85    0.005639
5 2021-03-22 09:30:00  ltc  LTCUSDT       0.85    0.541478
6 2021-03-22 09:30:00  xrp  XRPUSDT       0.85    0.909156
Traceback (most recent call last):
  File "app.py", line 168, in <module>
    quantity = buy(trader, coin, test=config.TEST, cash=config.CASH)
  File "app.py", line 61, in buy
    balance = float(trader.get_asset_balance(asset="USDT")["free"])
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1792, in get_asset_balance
    res = self.get_account(**params)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action.

**Comment by JonathanElejalde** [comment]
Hi! Did you try changing the api_key and secret_key? Apparently, the ones that you are using do not provide the necessary permissions.
